version=0.6.4
group=com.github.newvisualkeybing
java_version=21

minecraft_version=1.21.10
mod_name=NewVisualKeybing
mod_author=xinian
mod_id=newvisualkeybing
license=LGPL-3.0
credits=
description=The description of your mod. \nAccepts multilines.
minecraft_version_range=[1.21.10, 1.22)
neo_form_version=1.21.10-20251010.172816
parchment_minecraft=1.21.9
parchment_version=2025.10.05

fabric_version=0.135.0+1.21.10
fabric_loader_version=0.17.3

forge_version=60.0.3
forge_loader_version_range=[60,)

neoforge_version=21.10.8-beta
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
