version=0.5.21
group=com.github.newvisualkeybing
java_version=25

minecraft_version=26.1
mod_name=NewVisualKeybing
mod_author=xinian
mod_id=newvisualkeybing
license=ARR
credits=
description=The description of your mod. \nAccepts multilines.
minecraft_version_range=[26.1, 26.2)
neo_form_version=26.1-1

fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
